# department.py - Generated by Extractor Generator Tool
"""
DepartmentExtractor - Data extractor for DEPARTMENT table

Generated on: 2025-12-11 14:55:09
CSV Inputs: OfferedCourses, WorkLoad
Dependencies: None

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
from typing import Dict, List, Any
from base_extractor import DataExtractor


class DepartmentExtractor(DataExtractor):
    """Extract data for DEPARTMENT table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "DEPARTMENT"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return []
    
    def extract(self, OfferedCourses: pd.DataFrame, WorkLoad: pd.DataFrame, **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for DEPARTMENT table.
        
        Args:
        CSV Data:
            OfferedCourses: DataFrame loaded from OfferedCourses.csv
            WorkLoad: DataFrame loaded from WorkLoad.csv
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing DEPARTMENT table records
            
        Example structure:
        ```python
        records = []
        for index, row in some_dataframe.iterrows():
            record = {
                'COLUMN_1': row['source_column_1'],
                'COLUMN_2': row['source_column_2'],
                # Add more columns as needed
            }
            records.append(record)
        return records
        ```
        """

        # Combine all department-related columns
        all_departments = (
            OfferedCourses['srvProvider'].tolist() + 
            OfferedCourses['srvClient'].tolist() + 
            OfferedCourses['lecDept'].tolist()
        )

        # Remove duplicates and null values
        departments = pd.Series(all_departments).drop_duplicates().dropna().tolist()

        # Filter out empty strings and clean data
        clean_departments = []
        for dept in departments:
            if dept and str(dept).strip():
                clean_departments.append({'D_NAME': str(dept).strip()})
        
        return clean_departments
        
