# deputat_account.py - Generated by Extractor Generator Tool
"""
DeputatAccountExtractor - Data extractor for DEPUTAT_ACCOUNT table

Generated on: 2025-12-11 14:55:09
CSV Inputs: None
Dependencies: TEACHER, SEMESTER_PLANNING

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
import logging
from typing import Dict, List, Any
from base_extractor import DataExtractor

logger = logging.getLogger(__name__)


class DeputatAccountExtractor(DataExtractor):
    """Extract data for DEPUTAT_ACCOUNT table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "DEPUTAT_ACCOUNT"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return ['TEACHER', 'SEMESTER_PLANNING']
    
    def extract(self, teacher: List[Dict[str, Any]], semester_planning: List[Dict[str, Any]], professor: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for DEPUTAT_ACCOUNT table.
        
        Args:
        Dependencies:
            teacher: List of TEACHER table records from dependency resolution
            semester_planning: List of SEMESTER_PLANNING table records from dependency resolution
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing DEPUTAT_ACCOUNT table records
        """
        if not teacher or not semester_planning:
            logger.warning("Missing dependencies")
            return []
        
        records = []
        id_counter = 1
        
        for t in teacher:
            for sp in semester_planning:
                record = {
                    'ACC_ID': id_counter,
                    'FK_T_ID': t['T_ID'],
                    'FK_SP_ID': sp['SP_ID'],
                    'ACC_BASELINE_HOURS': 18.0 if t.get('T_ID') in {p['T_ID'] for p in professor} else 12.0,
                    'ACC_CARRYOVER': 0.0
                }
                records.append(record)
                id_counter += 1
        
        logger.info(f"{self.__class__.__name__} extracted {len(records)} records")
        return records
