# offering.py - Generated by Extractor Generator Tool
"""
OfferingExtractor - Data extractor for OFFERING table

Generated on: 2025-12-11 14:55:09
CSV Inputs: OfferedCourses
Dependencies: SUBJECT, SEMESTER_PLANNING

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
import logging
from typing import Dict, List, Any
from base_extractor import DataExtractor

logger = logging.getLogger(__name__)


class OfferingExtractor(DataExtractor):
    """Extract data for OFFERING table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "OFFERING"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return ['SUBJECT', 'SEMESTER_PLANNING']
    
    def extract(self, OfferedCourses: pd.DataFrame, subject: List[Dict[str, Any]], semester_planning: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for OFFERING table.
        
        Args:
        CSV Data:
            OfferedCourses: DataFrame loaded from OfferedCourses.csv
        Dependencies:
            subject: List of SUBJECT table records from dependency resolution
            semester_planning: List of SEMESTER_PLANNING table records from dependency resolution
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing OFFERING table records
        """
        if not subject or not semester_planning:
            logger.warning("Missing dependencies")
            return []
        
        def normalize_text(value: Any) -> str:
            if value is None or (isinstance(value, float) and pd.isna(value)):
                return None
            text = str(value).strip()
            if not text:
                return None
            return " ".join(text.split()).lower()

        def normalize_program(value: Any) -> str:
            if value is None or (isinstance(value, float) and pd.isna(value)):
                return None
            text = str(value).strip()
            if not text:
                return None
            return text.upper()

        def normalize_semester(value: Any) -> int:
            if value is None or (isinstance(value, float) and pd.isna(value)):
                return None
            try:
                return int(float(value))
            except (ValueError, TypeError):
                return None

        def normalize_term(value: Any) -> str:
            if value is None or (isinstance(value, float) and pd.isna(value)):
                return None
            text = str(value).strip()
            if not text:
                return None
            return text.upper()

        # Create lookups
        subject_lookup = {}
        for s in subject:
            key = (
                normalize_text(s.get('S_NAME')),
                normalize_semester(s.get('S_SEMESTER')),
                normalize_program(s.get('FK_ST_NAME')),
            )
            if None in key:
                continue
            if key in subject_lookup:
                logger.warning(f"Duplicate subject key {key}, keeping first match")
                continue
            subject_lookup[key] = s['S_ID']

        semester_lookup = {}
        for s in semester_planning:
            term_key = normalize_term(s.get('SP_TERM'))
            if term_key:
                semester_lookup[term_key] = s['SP_ID']
        
        # Get unique subject-term combinations
        df = OfferedCourses[['sbjName', 'sbjlevel', 'studyPrg', 'term', 'numSchd']].copy()
        df['sbjName_norm'] = df['sbjName'].apply(normalize_text)
        df['sbjlevel_norm'] = df['sbjlevel'].apply(normalize_semester)
        df['studyPrg_norm'] = df['studyPrg'].apply(normalize_program)
        df['term_norm'] = df['term'].apply(normalize_term)
        df['numSchd'] = pd.to_numeric(df['numSchd'], errors='coerce').fillna(0)

        df = df.dropna(subset=['sbjName_norm', 'sbjlevel_norm', 'studyPrg_norm', 'term_norm'])
        unique = (
            df.groupby(['sbjName_norm', 'sbjlevel_norm', 'studyPrg_norm', 'term_norm'], as_index=False)
            ['numSchd'].max()
        )
        
        records = []
        id_counter = 1
        
        missing_subject = 0
        missing_semester = 0
        for _, row in unique.iterrows():
            subject_key = (row['sbjName_norm'], row['sbjlevel_norm'], row['studyPrg_norm'])
            subject_id = subject_lookup.get(subject_key)
            sem_id = semester_lookup.get(row['term_norm'])

            if subject_id is None:
                missing_subject += 1
                continue
            if sem_id is None:
                missing_semester += 1
                continue
            
            record = {
                'O_ID': id_counter,
                'FK_S_ID': subject_id,
                'FK_SP_ID': sem_id,
                'O_PLANNED_HOURS': float(row['numSchd']),
            }
            records.append(record)
            id_counter += 1

        if missing_subject:
            logger.warning(f"{missing_subject} offerings skipped (subject not found)")
        if missing_semester:
            logger.warning(f"{missing_semester} offerings skipped (semester not found)")

        logger.info(f"{self.__class__.__name__} extracted {len(records)} records")
        return records
