# offering.py - Generated by Extractor Generator Tool
"""
OfferingExtractor - Data extractor for OFFERING table

Generated on: 2025-12-11 14:55:09
CSV Inputs: OfferedCourses
Dependencies: SUBJECT, SEMESTER_PLANNING

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
from typing import Dict, List, Any
from base_extractor import DataExtractor


class OfferingExtractor(DataExtractor):
    """Extract data for OFFERING table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "OFFERING"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return ['SUBJECT', 'SEMESTER_PLANNING']
    
    def extract(self, OfferedCourses: pd.DataFrame, subject: List[Dict[str, Any]], semester_planning: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:

        offeringDF = OfferedCourses[['sbjNo', 'term', 'numSchd', 'elective']].drop_duplicates() 

        # Map subject numbers to their IDs
        subject_nr_to_id = {s['S_NR']: s['S_ID'] for s in subject}

        # Map terms to their IDs
        term_name_to_id = {sem['SP_NAME']: sem['SP_ID'] for sem in semester_planning}

        # Replace subject numbers with their corresponding subject IDs
        offeringDF['S_ID'] = offeringDF['sbjNo'].map(subject_nr_to_id)

        # Replace terms with their corresponding semester planning IDs
        offeringDF['SP_ID'] = offeringDF['term'].map(term_name_to_id)

        result = []
        for i, offeringDF in enumerate(offeringDF.to_dict(orient='records')):
            offering = {
                'O_ID': i + 1,  # Auto-incrementing ID
                'FK_SUBJECT': offeringDF['S_ID'],  # Foreign key to SUBJECT.S_ID
                'FK_SEMESTER_PLANNING': offeringDF['SP_ID'],  # Foreign key to SEMESTER_PLANNING.SP_ID
                'O_PLANNED_HOURS': int(offeringDF['numSchd']) if not pd.isna(offeringDF['numSchd']) else 0,
                'O_TYPE': bool(offeringDF['elective']) if not pd.isna(offeringDF['elective']) else False
            }
            result.append(offering)

        return result