# offering_assignment.py - Generated by Extractor Generator Tool
"""
OfferingAssignmentExtractor - Data extractor for OFFERING_ASSIGNMENT table

Generated on: 2025-12-11 14:55:10
CSV Inputs: OfferedCourses
Dependencies: OFFERING, TEACHER

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
from typing import Dict, List, Any
from base_extractor import DataExtractor


class OfferingAssignmentExtractor(DataExtractor):
    """Extract data for OFFERING_ASSIGNMENT table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "OFFERING_ASSIGNMENT"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return ['OFFERING', 'TEACHER']
    
    def extract(self, OfferedCourses: pd.DataFrame, offering: List[Dict[str, Any]], teacher: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
        
        offeringAssignmentsDF = OfferedCourses[['sbjNo', 'lecName', 'lec1stn']].drop_duplicates()
