# position.py - Generated by Extractor Generator Tool
"""
PositionExtractor - Data extractor for POSITION table

Generated on: 2025-12-11 14:55:09
CSV Inputs: WorkLoad
Dependencies: None

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
from typing import Dict, List, Any
from base_extractor import DataExtractor


class PositionExtractor(DataExtractor):
    """Extract data for POSITION table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "POSITION"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return []
    
    def extract(self, WorkLoad: pd.DataFrame, **kwargs) -> List[Dict[str, Any]]:
        """
        Extract unique job titles and assign auto-incrementing IDs.
        Same logic as original getPositions function.
        """
        # Get unique job titles, remove duplicates and nulls
        positions = WorkLoad['job title'].drop_duplicates().dropna().tolist()
        
        result = []
        for i, position in enumerate(positions, 1):  # Start auto-increment at 1
            if position and str(position).strip():
                result.append({
                    'PO_ID': i,  # Auto-incrementing ID
                    'PO_NAME': str(position).strip()
                })
        
        return result
