# position_professor.py - Generated by Extractor Generator Tool
"""
PositionProfessorExtractor - Data extractor for POSITION_PROFESSOR table

Generated on: 2025-12-11 14:55:09
CSV Inputs: WorkLoad
Dependencies: PROFESSOR, POSITION, SEMESTER_PLANNING

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
import logging
from typing import Dict, List, Any
from base_extractor import DataExtractor

logger = logging.getLogger(__name__)


class PositionProfessorExtractor(DataExtractor):
    """Extract data for POSITION_PROFESSOR table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "POSITION_PROFESSOR"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return ['PROFESSOR', 'POSITION', 'SEMESTER_PLANNING']
    
    def extract(self, WorkLoad: pd.DataFrame, professor: List[Dict[str, Any]], position: List[Dict[str, Any]], semester_planning: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for POSITION_PROFESSOR table.
        
        Args:
        CSV Data:
            WorkLoad: DataFrame loaded from WorkLoad.csv
        Dependencies:
            professor: List of PROFESSOR table records from dependency resolution
            position: List of POSITION table records from dependency resolution
            semester_planning: List of SEMESTER_PLANNING table records from dependency resolution
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing POSITION_PROFESSOR table records
        """
        if not professor or not position:
            logger.warning("Missing dependencies")
            return []
        
        # Get TEACHER data for name lookup
        teacher_data = kwargs.get('teacher', [])
        teacher_by_name = {}
        for t in teacher_data:
            lastname = t.get('T_LASTNAME', '')
            if lastname:
                teacher_by_name[lastname] = t['T_ID']
        
        prof_ids = {p['P_ID'] for p in professor}
        position_by_name = {p['PO_NAME']: p['PO_ID'] for p in position}
        
        records = []
        
        for _, row in WorkLoad.iterrows():
            name = str(row['name']).strip() if not pd.isna(row['name']) else None
            job_title = str(row['job title']).strip() if not pd.isna(row['job title']) else None
            term = str(row['term']).strip() if not pd.isna(row['term']) else None
            reduction = pd.to_numeric(row['reduction'], errors='coerce')
            
            if not name or not job_title or pd.isna(reduction):
                continue
            
            teacher_id = teacher_by_name.get(name)
            if not teacher_id or teacher_id not in prof_ids:
                continue
            
            position_id = position_by_name.get(job_title)
            if not position_id:
                continue
            
            record = {
                'P_ID': teacher_id,
                'PO_ID': position_id,
                'TERM': term,
                'CREDIT_HOURS': float(reduction)
            }
            records.append(record)
        
        logger.info(f"{self.__class__.__name__} extracted {len(records)} records")
        return records

