# programm_subject_requirement.py - Generated by Extractor Generator Tool
"""
ProgrammSubjectRequirementExtractor - Data extractor for PROGRAMM_SUBJECT_REQUIREMENT table

Generated on: 2025-12-11 14:55:10
CSV Inputs: OfferedCourses
Dependencies: STUDY_PROGRAM, SUBJECT, SEMESTER_PLANNING

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
import logging
from typing import Dict, List, Any
from base_extractor import DataExtractor

logger = logging.getLogger(__name__)


class ProgrammSubjectRequirementExtractor(DataExtractor):
    """Extract data for PROGRAMM_SUBJECT_REQUIREMENT table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "PROGRAMM_SUBJECT_REQUIREMENT"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return ['STUDY_PROGRAM', 'SUBJECT', 'SEMESTER_PLANNING']
    
    def extract(self, OfferedCourses: pd.DataFrame, study_program: List[Dict[str, Any]], subject: List[Dict[str, Any]], semester_planning: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for PROGRAMM_SUBJECT_REQUIREMENT table.
        
        Args:
        CSV Data:
            OfferedCourses: DataFrame loaded from OfferedCourses.csv
        Dependencies:
            study_program: List of STUDY_PROGRAM table records from dependency resolution
            subject: List of SUBJECT table records from dependency resolution
            semester_planning: List of SEMESTER_PLANNING table records from dependency resolution
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing PROGRAMM_SUBJECT_REQUIREMENT table records
        """
        if not study_program or not subject or not semester_planning:
            logger.warning("Missing dependencies")
            return []
        
        study_prog_names = {sp['ST_NAME'] for sp in study_program}
        subject_lookup = {s['S_NR']: s for s in subject}
        semester_lookup = {s['SP_TERM']: s['SP_ID'] for s in semester_planning}
        
        df = OfferedCourses[['studyPrg', 'sbjNo', 'term', 'sbjlevel', 'numCurr']].copy()
        df = df.drop_duplicates(subset=['studyPrg', 'sbjNo', 'term'])
        
        records = []
        id_counter = 1
        
        for _, row in df.iterrows():
            prog = str(row['studyPrg']).strip()
            sbj_no = str(row['sbjNo']).strip()
            term = str(row['term']).strip()
            
            if prog not in study_prog_names or sbj_no not in subject_lookup or term not in semester_lookup:
                continue
            
            semester = pd.to_numeric(row['sbjlevel'], errors='coerce')
            if pd.isna(semester):
                semester = 1
            
            hours = pd.to_numeric(row['numCurr'], errors='coerce')
            if pd.isna(hours):
                hours = 0.0
            
            record = {
                'PSR_ID': id_counter,
                'FK_STUDY_PROGRAM': prog,
                'FK_SUBJECT': sbj_no,
                'FK_SEMESTER_PLANNING': semester_lookup[term],
                'PSR_REQUIRED_HOURS': float(hours),
                'PSR_TARGET_SEMESTER': int(semester),
                'PSR_ESTIMATED_NEEDS': None
            }
            records.append(record)
            id_counter += 1
        
        logger.info(f"{self.__class__.__name__} extracted {len(records)} records")
        return records

