# semester_planning.py - Generated by Extractor Generator Tool
"""
SemesterPlanningExtractor - Data extractor for SEMESTER_PLANNING table

Generated on: 2025-12-11 14:55:09
CSV Inputs: OfferedCourses, WorkLoad
Dependencies: None

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
import logging
from typing import Dict, List, Any
from base_extractor import DataExtractor

logger = logging.getLogger(__name__)


class SemesterPlanningExtractor(DataExtractor):
    """Extract data for SEMESTER_PLANNING table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "SEMESTER_PLANNING"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return []
    
    def extract(self, OfferedCourses: pd.DataFrame, WorkLoad: pd.DataFrame, **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for SEMESTER_PLANNING table.
        
        Args:
        CSV Data:
            OfferedCourses: DataFrame loaded from OfferedCourses.csv
            WorkLoad: DataFrame loaded from WorkLoad.csv
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing SEMESTER_PLANNING table records
        """
        # Extract unique terms from both CSVs
        terms_oc = OfferedCourses['term'].drop_duplicates().dropna().tolist()
        terms_wl = WorkLoad['term'].drop_duplicates().dropna().tolist()
        all_terms = list(set(terms_oc + terms_wl))
        
        records = []
        for idx, term in enumerate(sorted(all_terms), start=1):
            if term and str(term).strip():
                record = {
                    'SP_ID': idx,
                    'SP_TERM': str(term).strip(),
                    'SP_VERSION_NR': 1,
                    'SP_IS_FINAL': True
                }
                records.append(record)
        
        logger.info(f"{self.__class__.__name__} extracted {len(records)} records")
        return records
