# service_request.py - Generated by Extractor Generator Tool
"""
ServiceRequestExtractor - Data extractor for SERVICE_REQUEST table

Generated on: 2025-12-11 14:55:10
CSV Inputs: OfferedCourses
Dependencies: SUBJECT, SEMESTER_PLANNING, DEPARTMENT

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
import logging
from typing import Dict, List, Any
from base_extractor import DataExtractor

logger = logging.getLogger(__name__)


class ServiceRequestExtractor(DataExtractor):
    """Extract data for SERVICE_REQUEST table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "SERVICE_REQUEST"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return ['SUBJECT', 'SEMESTER_PLANNING', 'DEPARTMENT']
    
    def extract(self, OfferedCourses: pd.DataFrame, subject: List[Dict[str, Any]], semester_planning: List[Dict[str, Any]], department: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for SERVICE_REQUEST table.
        
        Args:
        CSV Data:
            OfferedCourses: DataFrame loaded from OfferedCourses.csv
        Dependencies:
            subject: List of SUBJECT table records from dependency resolution
            semester_planning: List of SEMESTER_PLANNING table records from dependency resolution
            department: List of DEPARTMENT table records from dependency resolution
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing SERVICE_REQUEST table records
        """
        if not subject or not semester_planning or not department:
            logger.warning("Missing dependencies")
            return []
        
        subject_lookup = {s['S_NR']: s for s in subject}
        semester_lookup = {s['SP_TERM']: s['SP_ID'] for s in semester_planning}
        dept_names = {d['D_NAME'] for d in department}
        
        # Filter for service courses (srvProvider != srvClient)
        df = OfferedCourses[OfferedCourses['srvProvider'] != OfferedCourses['srvClient']].copy()
        df = df[['sbjNo', 'term', 'srvProvider', 'srvClient', 'numSchd']].drop_duplicates()
        
        records = []
        id_counter = 1
        
        for _, row in df.iterrows():
            sbj_no = str(row['sbjNo']).strip()
            term = str(row['term']).strip()
            provider = str(row['srvProvider']).strip()
            client = str(row['srvClient']).strip()
            
            if sbj_no not in subject_lookup or term not in semester_lookup:
                continue
            if provider not in dept_names or client not in dept_names:
                continue
            
            hours = pd.to_numeric(row['numSchd'], errors='coerce')
            if pd.isna(hours):
                hours = 0.0
            
            record = {
                'SR_ID': id_counter,
                'FK_SUBJECT': sbj_no,
                'FK_SEMESTER_PLANNING': semester_lookup[term],
                'SR_EXPORTING_FACULTY': provider,
                'SR_IMPORTING_FACULTY': client,
                'SR_WEEKLY_HOURS': float(hours),
                'SR_STATUS': 'open'
            }
            records.append(record)
            id_counter += 1
        
        logger.info(f"{self.__class__.__name__} extracted {len(records)} records")
        return records

