# study_program.py - Generated by Extractor Generator Tool
"""
StudyProgramExtractor - Data extractor for STUDY_PROGRAM table

Generated on: 2025-12-11 14:55:09
CSV Inputs: OfferedCourses
Dependencies: None

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

from tkinter.font import names
import pandas as pd
from typing import Dict, List, Any
from base_extractor import DataExtractor


class StudyProgramExtractor(DataExtractor):
    """Extract data for STUDY_PROGRAM table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "STUDY_PROGRAM"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return []
    
    def extract(self, OfferedCourses: pd.DataFrame, **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for STUDY_PROGRAM table.
        
        Args:
        CSV Data:
            OfferedCourses: DataFrame loaded from OfferedCourses.csv
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing STUDY_PROGRAM table records
            
        TODO: Implement your extraction logic here
        Example structure:
        ```python
        records = []
        for index, row in some_dataframe.iterrows():
            record = {
                'COLUMN_1': row['source_column_1'],
                'COLUMN_2': row['source_column_2'],
                # Add more columns as needed
            }
            records.append(record)
        return records
        ```
        """
        studyPrograms = []
        for name in names:
            if not name or pd.isna(name):
                continue
            
            # Find most common department (srvClient) for this study program
            program_data = OfferedCourses[OfferedCourses['studyPrg'] == name]
            department_counts = program_data['srvClient'].value_counts()
            
            if len(department_counts) > 0:
                most_common_dept = department_counts.index[0]
                studyPrograms.append({
                    'ST_NAME': str(name),
                    'ST_DEPARTMENT': str(most_common_dept)
                })
        
        return studyPrograms