# subject.py - Generated by Extractor Generator Tool
"""
SubjectExtractor - Data extractor for SUBJECT table

Generated on: 2025-12-11 14:55:09
CSV Inputs: OfferedCourses
Dependencies: STUDY_PROGRAM

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
import logging
from typing import Dict, List, Any
from base_extractor import DataExtractor

class SubjectExtractor(DataExtractor):
    """Extract data for SUBJECT table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "SUBJECT"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on"""
        return ['STUDY_PROGRAM']
    
    def extract(self, OfferedCourses: pd.DataFrame, study_program: List[Dict[str, Any]], **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for SUBJECT table.
        
        Args:
        CSV Data:
            OfferedCourses: DataFrame loaded from OfferedCourses.csv
        Dependencies:
            study_program: List of STUDY_PROGRAM table records from dependency resolution
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing SUBJECT table records
        """
            
        # Get relevant columns and remove duplicates
        subjectsDF = OfferedCourses[[
            'sbjNo', 'sbjName', 'sbjlevel', 'sbjNotes', 'elective', 'studyPrg', 'numCurr'
        ]].drop_duplicates()
        
        def safe_numeric(value):
            """Convert numeric strings with comma decimal separator to float"""
            if pd.isna(value):
                return 0.0
            if isinstance(value, str):
                try:
                    return float(value.replace(',', '.'))
                except ValueError:
                    return 0.0
            return float(value)
        
        subjects = []
        for index, row in subjectsDF.iterrows():
            if pd.isna(row['sbjNo']):
                continue
            
            subject = {
                'S_ID': str(row['sbjNo']),  # Primary key (not auto-increment)
                'S_NAME': str(row['sbjName']) if not pd.isna(row['sbjName']) else None,
                'S_STUPO_HOURS': safe_numeric(row['numCurr']),
                'S_SEMESTER': int(row['sbjlevel']) if not pd.isna(row['sbjlevel']) else None,
                'FK_ST_NAME': str(row['studyPrg']) if not pd.isna(row['studyPrg']) else None,
                'S_NOTES': str(row['sbjNotes']) if not pd.isna(row['sbjNotes']) else None,
                'S_TYPE': str(row['elective']) if not pd.isna(row['elective']) else logging.warning(f"Missing elective type for subject {row['sbjNo']}") or 'P',
            }
            subjects.append(subject)
        
        # Sort by subject number (same as original)
        subjects = sorted(subjects, key=lambda x: x['S_ID'] or '')
        
        return subjects
