# teacher.py - Generated by Extractor Generator Tool
"""
TeacherExtractor - Data extractor for TEACHER table

Generated on: 2025-12-11 14:55:09
CSV Inputs: OfferedCourses, WorkLoad
Dependencies: None

This extractor follows the DataExtractor contract for the database population system.
Modify the extract() method to implement your specific business logic.
"""

import pandas as pd
from typing import Dict, List, Any
from base_extractor import DataExtractor
import logging
logger = logging.getLogger(__name__)


class TeacherExtractor(DataExtractor):
    """Extract data for TEACHER table"""
    
    @property
    def table_name(self) -> str:
        """Return the database table name this extractor targets"""
        return "TEACHER"
    
    @property
    def dependencies(self) -> List[str]:
        """Return list of table names this extractor depends on, aka all foreign key references"""
        return ['DEPARTMENT']
    
    def extract(self, OfferedCourses: pd.DataFrame, WorkLoad: pd.DataFrame, **kwargs) -> List[Dict[str, Any]]:
        """
        Extract data for TEACHER table.
        
        Args:
        CSV Data:
            OfferedCourses: DataFrame loaded from OfferedCourses.csv
            WorkLoad: DataFrame loaded from WorkLoad.csv
        Additional:
            **kwargs: Additional parameters passed by the extraction system
        
        Returns:
            List of dictionaries representing TEACHER table records
        """
        teachersDF = OfferedCourses[[
            'lecNo', 'lec1stn', 'lecName', 'lecDept', 'lecNotes', 'isprof'
        ]].drop_duplicates()
            
        teachers = []
        for index, row in teachersDF.iterrows():
            if pd.isna(row['lecNo']) or row['lecNo'] == 0:
                continue
            teacher = {
                'T_ID': int(row['lecNo']),
                'T_NAME': str(row['lec1stn']) if not pd.isna(row['lec1stn']) else None,
                'T_LASTNAME': str(row['lecName']) if not pd.isna(row['lecName']) else None,
                'T_DEPARTMENT': str(row['lecDept']) if not pd.isna(row['lecDept']) else None,
                'T_NOTES': str(row['lecNotes']) if not pd.isna(row['lecNotes']) else None,
                'T_ISPROFESSOR': row['isprof'] == 'WAHR'
                # Add more columns as needed
            }
            teachers.append(teacher)
        return teachers
