-- DB2 Database Creation Script
-- Planning Tool Database for University Course Planning System

-- Create the database
CREATE DATABASE PLANNINGTOOL;

-- Connect to the new database
CONNECT TO PLANNINGTOOL;

-- Create the schema
CREATE SCHEMA PLANNING_TOOL;

-- Set the current schema
SET CURRENT SCHEMA = PLANNING_TOOL;

-- Create all tables with proper DB2 syntax

-- Base tables (no dependencies)
CREATE TABLE DEPARTMENT (
    D_NAME VARCHAR(3) NOT NULL,
    PRIMARY KEY (D_NAME)
);

CREATE TABLE POSITION (
    PO_ID INTEGER NOT NULL,
    PO_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (PO_ID)
);

CREATE TABLE SEMESTER_PLANNING (
    SP_ID INTEGER NOT NULL,
    SP_TERM VARCHAR(6) NOT NULL,
    SP_VERSION_NR INTEGER NOT NULL,
    SP_IS_FINAL SMALLINT NOT NULL,  -- DB2 doesn't have BOOLEAN, using SMALLINT (0/1)
    PRIMARY KEY (SP_ID)
);

CREATE TABLE STUDY_PROGRAM (
    ST_NAME VARCHAR(3) NOT NULL,
    ST_DEPARTMENT VARCHAR(3) NOT NULL,
    PRIMARY KEY (ST_NAME)
);

-- First level dependencies
CREATE TABLE TEACHER (
    T_ID INTEGER NOT NULL,
    T_DEPARTMENT VARCHAR(3) NOT NULL,
    T_NAME VARCHAR(40) NOT NULL,
    T_LASTNAME VARCHAR(40) NOT NULL,
    T_NOTES VARCHAR(100),
    T_ISPROFESSOR SMALLINT NOT NULL,  -- DB2 BOOLEAN as SMALLINT (0/1)
    PRIMARY KEY (T_ID),
    FOREIGN KEY (T_DEPARTMENT) REFERENCES DEPARTMENT(D_NAME)
);

CREATE TABLE SUBJECT (
    S_NR VARCHAR(11) NOT NULL,
    S_STUDY_PROGRAM VARCHAR(3) NOT NULL,
    S_NAME VARCHAR(100) NOT NULL,
    S_SEMESTER INTEGER NOT NULL,
    S_STUPO_HOURS DECIMAL(5,2) NOT NULL,
    S_SCHEDULE_HOURS DECIMAL(5,2) NOT NULL,
    S_COMMENT VARCHAR(100),
    S_TYPE VARCHAR(14) NOT NULL,
    PRIMARY KEY (S_NR),
    FOREIGN KEY (S_STUDY_PROGRAM) REFERENCES STUDY_PROGRAM(ST_NAME)
);

-- Second level dependencies
CREATE TABLE PROFESSOR (
    P_ID INTEGER NOT NULL,
    P_CREDIT_HOUR_ACCOUNT INTEGER,
    P_ROOM VARCHAR(10) NOT NULL,
    PRIMARY KEY (P_ID),
    FOREIGN KEY (P_ID) REFERENCES TEACHER(T_ID)
);

CREATE TABLE LECTURER (
    T_ID INTEGER NOT NULL,
    L_SUPERVISOR INTEGER NOT NULL,
    L_STREET_ADDRESS VARCHAR(100),
    L_CITY VARCHAR(30),
    L_ZIP VARCHAR(30),
    PRIMARY KEY (T_ID),
    FOREIGN KEY (T_ID) REFERENCES TEACHER(T_ID),
    FOREIGN KEY (L_SUPERVISOR) REFERENCES TEACHER(T_ID)
);

CREATE TABLE OFFERING (
    O_ID INTEGER NOT NULL,
    FK_SUBJECT VARCHAR(11) NOT NULL,
    FK_SEMESTER_PLANNING INTEGER NOT NULL,
    O_PLANNED_HOURS DECIMAL(5,2) NOT NULL,
    O_TYPE SMALLINT,  -- DB2 BOOLEAN as SMALLINT (0/1) - elective flag
    PRIMARY KEY (O_ID),
    FOREIGN KEY (FK_SUBJECT) REFERENCES SUBJECT(S_NR),
    FOREIGN KEY (FK_SEMESTER_PLANNING) REFERENCES SEMESTER_PLANNING(SP_ID)
);

-- Third level dependencies
CREATE TABLE OFFERING_ASSIGNMENT (
    OA_ID INTEGER NOT NULL,
    FK_OFFERING INTEGER NOT NULL,
    FK_TEACHER INTEGER NOT NULL,
    OA_ROLE VARCHAR(10),
    OA_ASSIGNED_HOURS DECIMAL(5,2),
    PRIMARY KEY (OA_ID),
    FOREIGN KEY (FK_OFFERING) REFERENCES OFFERING(O_ID),
    FOREIGN KEY (FK_TEACHER) REFERENCES TEACHER(T_ID)
);

CREATE TABLE COURSE (
    C_ID INTEGER NOT NULL,
    C_TEACHER INTEGER NOT NULL,
    C_SUBJECT VARCHAR(11) NOT NULL,
    C_ACTUAL_STUPO_HOURS DECIMAL(5,2),
    C_ACTUAL_SCHEDULE_HOURS DECIMAL(5,2),
    C_CREDITED_HOURS DECIMAL(5,2),
    C_TEACHER_COMMENT VARCHAR(100),
    C_SEMESTER VARCHAR(4),
    FK_OFFERING INTEGER NOT NULL,
    PRIMARY KEY (C_ID),
    FOREIGN KEY (C_TEACHER) REFERENCES TEACHER(T_ID),
    FOREIGN KEY (C_SUBJECT) REFERENCES SUBJECT(S_NR),
    FOREIGN KEY (FK_OFFERING) REFERENCES OFFERING(O_ID)
);

CREATE TABLE POSITION_PROFESSOR (
    P_ID INTEGER NOT NULL,
    PO_ID INTEGER NOT NULL,
    TERM VARCHAR(6) NOT NULL,
    CREDIT_HOURS DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (P_ID, PO_ID, TERM),
    FOREIGN KEY (P_ID) REFERENCES PROFESSOR(P_ID),
    FOREIGN KEY (PO_ID) REFERENCES POSITION(PO_ID)
);

CREATE TABLE DEPUTAT_ACCOUNT (
    ACC_ID INTEGER NOT NULL,
    FK_TEACHER INTEGER NOT NULL,
    FK_SEMESTER_PLANNING INTEGER NOT NULL,
    ACC_BASELINE_HOURS DECIMAL(5,2),
    ACC_CREDIT_HOURS DECIMAL(5,2),
    ACC_DEBIT_HOURS DECIMAL(5,2),
    ACC_BALANCE DECIMAL(5,2),
    ACC_CARRYOVER DECIMAL(5,2),
    PRIMARY KEY (ACC_ID),
    FOREIGN KEY (FK_TEACHER) REFERENCES TEACHER(T_ID),
    FOREIGN KEY (FK_SEMESTER_PLANNING) REFERENCES SEMESTER_PLANNING(SP_ID)
);

CREATE TABLE SERVICE_REQUEST (
    SR_ID INTEGER NOT NULL,
    FK_SUBJECT VARCHAR(11) NOT NULL,
    FK_SEMESTER_PLANNING INTEGER NOT NULL,
    SR_EXPORTING_FACULTY VARCHAR(3) NOT NULL,
    SR_IMPORTING_FACULTY VARCHAR(3) NOT NULL,
    SR_WEEKLY_HOURS DECIMAL(5,2),
    SR_STATUS VARCHAR(4),
    PRIMARY KEY (SR_ID),
    FOREIGN KEY (FK_SUBJECT) REFERENCES SUBJECT(S_NR),
    FOREIGN KEY (FK_SEMESTER_PLANNING) REFERENCES SEMESTER_PLANNING(SP_ID),
    FOREIGN KEY (SR_EXPORTING_FACULTY) REFERENCES DEPARTMENT(D_NAME),
    FOREIGN KEY (SR_IMPORTING_FACULTY) REFERENCES DEPARTMENT(D_NAME)
);

CREATE TABLE PROGRAMM_SUBJECT_REQUIREMENT (
    PSR_ID INTEGER NOT NULL,
    FK_STUDY_PROGRAM VARCHAR(3) NOT NULL,
    FK_SUBJECT VARCHAR(11) NOT NULL,
    FK_SEMESTER_PLANNING INTEGER NOT NULL,
    PSR_REQUIRED_HOURS DECIMAL(5,2),
    PSR_TARGET_SEMESTER INTEGER NOT NULL,
    PSR_ESTIMATED_NEEDS VARCHAR(100),
    PRIMARY KEY (PSR_ID),
    FOREIGN KEY (FK_STUDY_PROGRAM) REFERENCES STUDY_PROGRAM(ST_NAME),
    FOREIGN KEY (FK_SUBJECT) REFERENCES SUBJECT(S_NR),
    FOREIGN KEY (FK_SEMESTER_PLANNING) REFERENCES SEMESTER_PLANNING(SP_ID)
);

-- Create indexes for better performance
CREATE INDEX IDX_TEACHER_DEPT ON TEACHER(T_DEPARTMENT);
CREATE INDEX IDX_SUBJECT_PROGRAM ON SUBJECT(S_STUDY_PROGRAM);
CREATE INDEX IDX_OFFERING_SUBJECT ON OFFERING(FK_SUBJECT);
CREATE INDEX IDX_OFFERING_SEMESTER ON OFFERING(FK_SEMESTER_PLANNING);
CREATE INDEX IDX_COURSE_TEACHER ON COURSE(C_TEACHER);
CREATE INDEX IDX_COURSE_OFFERING ON COURSE(FK_OFFERING);
CREATE INDEX IDX_OA_OFFERING ON OFFERING_ASSIGNMENT(FK_OFFERING);
CREATE INDEX IDX_OA_TEACHER ON OFFERING_ASSIGNMENT(FK_TEACHER);

COMMIT;

-- Show created tables
SELECT TABNAME FROM SYSCAT.TABLES WHERE TABSCHEMA = 'PLANNING_TOOL' ORDER BY TABNAME;