-- DB2 database creation script for PLANTOOL
-- Creates database, schema, tables, and inline foreign keys.

CREATE DATABASE PLANTOOL;

CONNECT TO PLANTOOL;

CREATE SCHEMA PLANTOOL;

-- Table DEPARTMENT
CREATE TABLE PLANTOOL.DEPARTMENT (
  D_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (D_NAME)
);

-- Table POSTAL_CODE
CREATE TABLE PLANTOOL.POSTAL_CODE (
  ZIP VARCHAR(10) NOT NULL,
  CITY VARCHAR(100) NOT NULL,
  PRIMARY KEY (ZIP)
);

-- Table SEMESTER_PLANNING
CREATE TABLE PLANTOOL.SEMESTER_PLANNING (
  SP_ID INT NOT NULL,
  SP_TERM VARCHAR(20) NOT NULL,
  SP_VERSION_NR INT NOT NULL,
  SP_IS_FINAL SMALLINT NOT NULL,
  PRIMARY KEY (SP_ID)
);

-- Table POSITION
CREATE TABLE PLANTOOL.POSITION (
  PO_ID INT NOT NULL,
  PO_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (PO_ID)
);

-- Table TEACHER
CREATE TABLE PLANTOOL.TEACHER (
  T_ID INT NOT NULL,
  T_NAME VARCHAR(100),
  T_LASTNAME VARCHAR(100) NOT NULL,
  FK_D_NAME VARCHAR(100),
  FK_ZIP VARCHAR(10),
  T_NOTES VARCHAR(100),
  T_IS_ACTIVE SMALLINT NOT NULL,
  PRIMARY KEY (T_ID),
  CONSTRAINT fk_TEACHER_DEPARTMENT
    FOREIGN KEY (FK_D_NAME) REFERENCES PLANTOOL.DEPARTMENT (D_NAME),
  CONSTRAINT fk_TEACHER_POSTAL_CODE
    FOREIGN KEY (FK_ZIP) REFERENCES PLANTOOL.POSTAL_CODE (ZIP)
);

-- Table PROFESSOR
CREATE TABLE PLANTOOL.PROFESSOR (
  T_ID INT NOT NULL,
  P_ROOM VARCHAR(50),
  PRIMARY KEY (T_ID),
  CONSTRAINT fk_PROFESSOR_TEACHER
    FOREIGN KEY (T_ID) REFERENCES PLANTOOL.TEACHER (T_ID)
);

-- Table LECTURER
CREATE TABLE PLANTOOL.LECTURER (
  T_ID INT NOT NULL,
  L_STREET_ADDRESS VARCHAR(255),
  PRIMARY KEY (T_ID),
  CONSTRAINT fk_LECTURER_TEACHER
    FOREIGN KEY (T_ID) REFERENCES PLANTOOL.TEACHER (T_ID)
);

-- Table STUDY_PROGRAM
CREATE TABLE PLANTOOL.STUDY_PROGRAM (
  ST_NAME VARCHAR(100) NOT NULL,
  FK_D_NAME VARCHAR(100),
  PRIMARY KEY (ST_NAME),
  CONSTRAINT fk_STUDY_PROGRAM_DEPARTMENT
    FOREIGN KEY (FK_D_NAME) REFERENCES PLANTOOL.DEPARTMENT (D_NAME)
);

-- Table SUBJECT
CREATE TABLE PLANTOOL.SUBJECT (
  S_ID INT NOT NULL,
  S_NAME VARCHAR(255) NOT NULL,
  S_STUPO_HOURS DECIMAL(4,2),
  S_SEMESTER INT NOT NULL,
  FK_ST_NAME VARCHAR(100),
  S_NOTES VARCHAR(100),
  S_TYPE VARCHAR(1) NOT NULL,
  PRIMARY KEY (S_ID),
  CONSTRAINT fk_SUBJECT_STUDY_PROGRAM
    FOREIGN KEY (FK_ST_NAME) REFERENCES PLANTOOL.STUDY_PROGRAM (ST_NAME)
);

-- Table OFFERING
CREATE TABLE PLANTOOL.OFFERING (
  O_ID INT NOT NULL,
  FK_S_ID INT,
  FK_SP_ID INT,
  O_PLANNED_HOURS INT,
  PRIMARY KEY (O_ID),
  CONSTRAINT fk_OFFERING_SUBJECT
    FOREIGN KEY (FK_S_ID) REFERENCES PLANTOOL.SUBJECT (S_ID),
  CONSTRAINT fk_OFFERING_SEMESTER_PLANNING
    FOREIGN KEY (FK_SP_ID) REFERENCES PLANTOOL.SEMESTER_PLANNING (SP_ID)
);

-- Table OFFERING_ASSIGNMENT
CREATE TABLE PLANTOOL.OFFERING_ASSIGNMENT (
  OA_ID INT NOT NULL,
  FK_O_ID INT,
  FK_T_ID INT,
  OA_ASSIGNED_HOURS DECIMAL(4,2),
  OA_ROLE VARCHAR(50),
  PRIMARY KEY (OA_ID),
  CONSTRAINT fk_OFFERING_ASSIGNMENT_OFFERING
    FOREIGN KEY (FK_O_ID) REFERENCES PLANTOOL.OFFERING (O_ID),
  CONSTRAINT fk_OFFERING_ASSIGNMENT_TEACHER
    FOREIGN KEY (FK_T_ID) REFERENCES PLANTOOL.TEACHER (T_ID)
);

-- Table DEPUTAT_ACCOUNT
CREATE TABLE PLANTOOL.DEPUTAT_ACCOUNT (
  ACC_ID INT NOT NULL,
  FK_T_ID INT,
  FK_SP_ID INT,
  ACC_BASELINE_HOURS DECIMAL(4,2),
  ACC_CARRYOVER DECIMAL(4,2),
  PRIMARY KEY (ACC_ID),
  CONSTRAINT fk_DEPUTAT_ACCOUNT_TEACHER
    FOREIGN KEY (FK_T_ID) REFERENCES PLANTOOL.TEACHER (T_ID),
  CONSTRAINT fk_DEPUTAT_ACCOUNT_SEMESTER_PLANNING
    FOREIGN KEY (FK_SP_ID) REFERENCES PLANTOOL.SEMESTER_PLANNING (SP_ID)
);

-- Table SERVICE_REQUEST
CREATE TABLE PLANTOOL.SERVICE_REQUEST (
  SR_ID INT NOT NULL,
  FK_S_ID INT,
  FK_REQUESTING_D_NAME VARCHAR(100),
  FK_PROVIDING_D_NAME VARCHAR(100),
  SR_HOURS DECIMAL(4,2) NOT NULL,
  SR_STATUS VARCHAR(50),
  FK_SEMESTER INT,
  SR_NOTES VARCHAR(100),
  PRIMARY KEY (SR_ID),
  CONSTRAINT fk_SERVICE_REQUEST_SUBJECT
    FOREIGN KEY (FK_S_ID) REFERENCES PLANTOOL.SUBJECT (S_ID),
  CONSTRAINT fk_SERVICE_REQUEST_REQUESTING_DEPT
    FOREIGN KEY (FK_REQUESTING_D_NAME) REFERENCES PLANTOOL.DEPARTMENT (D_NAME),
  CONSTRAINT fk_SERVICE_REQUEST_PROVIDING_DEPT
    FOREIGN KEY (FK_PROVIDING_D_NAME) REFERENCES PLANTOOL.DEPARTMENT (D_NAME),
  CONSTRAINT fk_SERVICE_REQUEST_SEMESTER_PLANNING
    FOREIGN KEY (FK_SEMESTER) REFERENCES PLANTOOL.SEMESTER_PLANNING (SP_ID)
);

-- Table POSITION_SEMESTER
CREATE TABLE PLANTOOL.POSITION_SEMESTER (
  PS_ID INT NOT NULL,
  FK_PO_ID INT NOT NULL,
  FK_SP_ID INT NOT NULL,
  PRIMARY KEY (PS_ID),
  CONSTRAINT fk_POSITION_SEMESTER_POSITION
    FOREIGN KEY (FK_PO_ID) REFERENCES PLANTOOL.POSITION (PO_ID),
  CONSTRAINT fk_POSITION_SEMESTER_SEMESTER_PLANNING
    FOREIGN KEY (FK_SP_ID) REFERENCES PLANTOOL.SEMESTER_PLANNING (SP_ID)
);

-- Table POSITION_ASSIGNMENT
CREATE TABLE PLANTOOL.POSITION_ASSIGNMENT (
  PA_ID INT NOT NULL,
  FK_PS_ID INT NOT NULL,
  FK_P_ID INT NOT NULL,
  PA_REDUCTION_HOURS DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (PA_ID),
  CONSTRAINT fk_POSITION_ASSIGNMENT_POSITION_SEMESTER
    FOREIGN KEY (FK_PS_ID) REFERENCES PLANTOOL.POSITION_SEMESTER (PS_ID),
  CONSTRAINT fk_POSITION_ASSIGNMENT_PROFESSOR
    FOREIGN KEY (FK_P_ID) REFERENCES PLANTOOL.PROFESSOR (T_ID)
);

CONNECT RESET;
