-- DB2 database creation script for PLANNING_TOOL
-- Creates database, schema, tables, and inline foreign keys.

CREATE DATABASE PLANTOOL;

CONNECT TO PLANTOOL;

CREATE SCHEMA PLANNING_TOOL;

-- Table DEPARTMENT
CREATE TABLE PLANNING_TOOL.DEPARTMENT (
  D_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (D_NAME)
);

-- Table POSTAL_CODE
CREATE TABLE PLANNING_TOOL.POSTAL_CODE (
  ZIP VARCHAR(10) NOT NULL,
  CITY VARCHAR(100) NOT NULL,
  PRIMARY KEY (ZIP)
);

-- Table SEMESTER_PLANNING
CREATE TABLE PLANNING_TOOL.SEMESTER_PLANNING (
  SP_ID INT NOT NULL,
  SP_TERM VARCHAR(20) NOT NULL,
  SP_VERSION_NR INT NOT NULL,
  SP_IS_FINAL SMALLINT NOT NULL,
  PRIMARY KEY (SP_ID)
);

-- Table POSITION
CREATE TABLE PLANNING_TOOL.POSITION (
  PO_ID INT NOT NULL,
  PO_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (PO_ID)
);

-- Table TEACHER
CREATE TABLE PLANNING_TOOL.TEACHER (
  T_ID INT NOT NULL,
  T_NAME VARCHAR(100),
  T_LASTNAME VARCHAR(100) NOT NULL,
  FK_D_NAME VARCHAR(100),
  FK_ZIP VARCHAR(10),
  T_NOTES VARCHAR(100),
  T_IS_ACTIVE SMALLINT NOT NULL,
  PRIMARY KEY (T_ID),
  CONSTRAINT fk_TEACHER_DEPARTMENT
    FOREIGN KEY (FK_D_NAME) REFERENCES PLANNING_TOOL.DEPARTMENT (D_NAME),
  CONSTRAINT fk_TEACHER_POSTAL_CODE
    FOREIGN KEY (FK_ZIP) REFERENCES PLANNING_TOOL.POSTAL_CODE (ZIP)
);

-- Table PROFESSOR
CREATE TABLE PLANNING_TOOL.PROFESSOR (
  T_ID INT NOT NULL,
  P_ROOM VARCHAR(50),
  PRIMARY KEY (T_ID),
  CONSTRAINT fk_PROFESSOR_TEACHER
    FOREIGN KEY (T_ID) REFERENCES PLANNING_TOOL.TEACHER (T_ID)
);

-- Table LECTURER
CREATE TABLE PLANNING_TOOL.LECTURER (
  T_ID INT NOT NULL,
  L_STREET_ADDRESS VARCHAR(255),
  L_SUPERVISOR INT,
  PRIMARY KEY (T_ID),
  CONSTRAINT fk_LECTURER_TEACHER
    FOREIGN KEY (T_ID) REFERENCES PLANNING_TOOL.TEACHER (T_ID),
  CONSTRAINT fk_LECTURER_SUPERVISOR
    FOREIGN KEY (L_SUPERVISOR) REFERENCES PLANNING_TOOL.PROFESSOR (T_ID)
);

-- Table STUDY_PROGRAM
CREATE TABLE PLANNING_TOOL.STUDY_PROGRAM (
  ST_NAME VARCHAR(100) NOT NULL,
  FK_D_NAME VARCHAR(100),
  PRIMARY KEY (ST_NAME),
  CONSTRAINT fk_STUDY_PROGRAM_DEPARTMENT
    FOREIGN KEY (FK_D_NAME) REFERENCES PLANNING_TOOL.DEPARTMENT (D_NAME)
);

-- Table SUBJECT
CREATE TABLE PLANNING_TOOL.SUBJECT (
  S_ID INT NOT NULL,
  S_NAME VARCHAR(255) NOT NULL,
  S_STUPO_HOURS DECIMAL(4,2),
  S_SEMESTER INT NOT NULL,
  FK_ST_NAME VARCHAR(100),
  S_NOTES VARCHAR(100),
  S_TYPE VARCHAR(1) NOT NULL,
  PRIMARY KEY (S_ID),
  CONSTRAINT fk_SUBJECT_STUDY_PROGRAM
    FOREIGN KEY (FK_ST_NAME) REFERENCES PLANNING_TOOL.STUDY_PROGRAM (ST_NAME)
);

-- Table OFFERING
CREATE TABLE PLANNING_TOOL.OFFERING (
  O_ID INT NOT NULL,
  FK_S_ID INT,
  FK_SP_ID INT,
  O_PLANNED_HOURS INT,
  PRIMARY KEY (O_ID),
  CONSTRAINT fk_OFFERING_SUBJECT
    FOREIGN KEY (FK_S_ID) REFERENCES PLANNING_TOOL.SUBJECT (S_ID),
  CONSTRAINT fk_OFFERING_SEMESTER_PLANNING
    FOREIGN KEY (FK_SP_ID) REFERENCES PLANNING_TOOL.SEMESTER_PLANNING (SP_ID)
);

-- Table OFFERING_ASSIGNMENT
CREATE TABLE PLANNING_TOOL.OFFERING_ASSIGNMENT (
  OA_ID INT NOT NULL,
  FK_O_ID INT,
  FK_T_ID INT,
  OA_ASSIGNED_HOURS DECIMAL(4,2),
  OA_ACTUAL_HOURS DECIMAL(4,2),
  OA_ROLE VARCHAR(50),
  PRIMARY KEY (OA_ID),
  CONSTRAINT fk_OFFERING_ASSIGNMENT_OFFERING
    FOREIGN KEY (FK_O_ID) REFERENCES PLANNING_TOOL.OFFERING (O_ID),
  CONSTRAINT fk_OFFERING_ASSIGNMENT_TEACHER
    FOREIGN KEY (FK_T_ID) REFERENCES PLANNING_TOOL.TEACHER (T_ID)
);

-- Table DEPUTAT_ACCOUNT
CREATE TABLE PLANNING_TOOL.DEPUTAT_ACCOUNT (
  ACC_ID INT NOT NULL,
  FK_T_ID INT,
  FK_SP_ID INT,
  ACC_BASELINE_HOURS DECIMAL(4,2),
  ACC_CARRYOVER DECIMAL(4,2),
  PRIMARY KEY (ACC_ID),
  CONSTRAINT fk_DEPUTAT_ACCOUNT_TEACHER
    FOREIGN KEY (FK_T_ID) REFERENCES PLANNING_TOOL.TEACHER (T_ID),
  CONSTRAINT fk_DEPUTAT_ACCOUNT_SEMESTER_PLANNING
    FOREIGN KEY (FK_SP_ID) REFERENCES PLANNING_TOOL.SEMESTER_PLANNING (SP_ID)
);

-- Table SERVICE_REQUEST
CREATE TABLE PLANNING_TOOL.SERVICE_REQUEST (
  SR_ID INT NOT NULL,
  FK_S_ID INT,
  FK_REQUESTING_D_NAME VARCHAR(100),
  FK_PROVIDING_D_NAME VARCHAR(100),
  SR_HOURS DECIMAL(4,2) NOT NULL,
  SR_STATUS VARCHAR(50),
  FK_SEMESTER INT,
  SR_NOTES VARCHAR(100),
  PRIMARY KEY (SR_ID),
  CONSTRAINT fk_SERVICE_REQUEST_SUBJECT
    FOREIGN KEY (FK_S_ID) REFERENCES PLANNING_TOOL.SUBJECT (S_ID),
  CONSTRAINT fk_SERVICE_REQUEST_REQUESTING_DEPT
    FOREIGN KEY (FK_REQUESTING_D_NAME) REFERENCES PLANNING_TOOL.DEPARTMENT (D_NAME),
  CONSTRAINT fk_SERVICE_REQUEST_PROVIDING_DEPT
    FOREIGN KEY (FK_PROVIDING_D_NAME) REFERENCES PLANNING_TOOL.DEPARTMENT (D_NAME),
  CONSTRAINT fk_SERVICE_REQUEST_SEMESTER_PLANNING
    FOREIGN KEY (FK_SEMESTER) REFERENCES PLANNING_TOOL.SEMESTER_PLANNING (SP_ID)
);

-- Table POSITION_SEMESTER
CREATE TABLE PLANNING_TOOL.POSITION_SEMESTER (
  PS_ID INT NOT NULL,
  FK_PO_ID INT NOT NULL,
  FK_SP_ID INT NOT NULL,
  PRIMARY KEY (PS_ID),
  CONSTRAINT fk_POSITION_SEMESTER_POSITION
    FOREIGN KEY (FK_PO_ID) REFERENCES PLANNING_TOOL.POSITION (PO_ID),
  CONSTRAINT fk_POSITION_SEMESTER_SEMESTER_PLANNING
    FOREIGN KEY (FK_SP_ID) REFERENCES PLANNING_TOOL.SEMESTER_PLANNING (SP_ID)
);

-- Table POSITION_ASSIGNMENT
CREATE TABLE PLANNING_TOOL.POSITION_ASSIGNMENT (
  PA_ID INT NOT NULL,
  FK_PS_ID INT NOT NULL,
  FK_P_ID INT NOT NULL,
  PA_REDUCTION_HOURS DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (PA_ID),
  CONSTRAINT fk_POSITION_ASSIGNMENT_POSITION_SEMESTER
    FOREIGN KEY (FK_PS_ID) REFERENCES PLANNING_TOOL.POSITION_SEMESTER (PS_ID),
  CONSTRAINT fk_POSITION_ASSIGNMENT_PROFESSOR
    FOREIGN KEY (FK_P_ID) REFERENCES PLANNING_TOOL.PROFESSOR (T_ID)
);

-- View: actual teaching workload per teacher and semester
CREATE VIEW PLANNING_TOOL.TEACHER_ACTUAL_WORKLOAD AS
SELECT
  T.T_ID,
  T.T_NAME,
  T.T_LASTNAME,
  COALESCE(SUM(OA.OA_ACTUAL_HOURS), 0) AS ACTUAL_HOURS,
  SP.SP_TERM
FROM PLANNING_TOOL.TEACHER T
JOIN PLANNING_TOOL.OFFERING_ASSIGNMENT OA ON OA.FK_T_ID = T.T_ID
JOIN PLANNING_TOOL.OFFERING O ON O.O_ID = OA.FK_O_ID
JOIN PLANNING_TOOL.SEMESTER_PLANNING SP ON SP.SP_ID = O.FK_SP_ID
GROUP BY T.T_ID, T.T_NAME, T.T_LASTNAME, SP.SP_TERM;

-- View: estimated workload per professor and semester
CREATE VIEW PLANNING_TOOL.PROFESSOR_ESTIMATED_WORKLOAD AS
SELECT
  T.T_ID,
  T.T_NAME,
  T.T_LASTNAME,
  COALESCE(SUM(OA.OA_ASSIGNED_HOURS), 0) AS ASSIGNED_HOURS,
  COALESCE(SUM(PA.PA_REDUCTION_HOURS), 0) AS REDUCTION_HOURS,
  COALESCE(SUM(OA.OA_ASSIGNED_HOURS), 0) + COALESCE(SUM(PA.PA_REDUCTION_HOURS), 0) AS TOTAL_WORKLOAD,
  SP.SP_TERM
FROM PLANNING_TOOL.TEACHER T
LEFT JOIN PLANNING_TOOL.OFFERING_ASSIGNMENT OA ON OA.FK_T_ID = T.T_ID
LEFT JOIN PLANNING_TOOL.OFFERING O ON O.O_ID = OA.FK_O_ID
LEFT JOIN PLANNING_TOOL.POSITION_ASSIGNMENT PA ON PA.FK_P_ID = T.T_ID
LEFT JOIN PLANNING_TOOL.POSITION_SEMESTER PS ON PS.PS_ID = PA.FK_PS_ID
LEFT JOIN PLANNING_TOOL.SEMESTER_PLANNING SP ON SP.SP_ID = COALESCE(O.FK_SP_ID, PS.FK_SP_ID)
GROUP BY T.T_ID, T.T_NAME, T.T_LASTNAME, SP.SP_TERM;

-- View: offered courses per study program and semester
CREATE VIEW PLANNING_TOOL.STUDY_PROGRAM_OFFERED_COURSES AS
SELECT
  S.S_ID,
  S.S_NAME,
  S.S_SEMESTER,
  SP.ST_NAME,
  O.FK_SP_ID,
  SEM.SP_TERM
FROM PLANNING_TOOL.OFFERING O
JOIN PLANNING_TOOL.SUBJECT S ON S.S_ID = O.FK_S_ID
LEFT JOIN PLANNING_TOOL.STUDY_PROGRAM SP ON SP.ST_NAME = S.FK_ST_NAME
LEFT JOIN PLANNING_TOOL.SEMESTER_PLANNING SEM ON SEM.SP_ID = O.FK_SP_ID;

CONNECT RESET;
