-- Generated DB2 DDL from dbschema/schema.dbs
-- Schema: Planning_Tool

CREATE SCHEMA Planning_Tool;

-- Table COURSE
CREATE TABLE Planning_Tool.COURSE (
  C_ID INT NOT NULL,
  C_TEACHER INT NOT NULL,
  C_SUBJECT VARCHAR(11) NOT NULL,
  C_ACTUAL_STUPO_HOURS DECIMAL(5,2),
  C_ACTUAL_SCHEDULE_HOURS DECIMAL(5,2),
  C_CREDITED_HOURS DECIMAL(5,2),
  C_TEACHER_COMMENT VARCHAR(100),
  C_SEMESTER VARCHAR(4),
  FK_OFFERING INT NOT NULL
  , PRIMARY KEY (C_ID)
)
;

-- Table DEPARTMENT
CREATE TABLE Planning_Tool.DEPARTMENT (
  D_NAME VARCHAR(3) NOT NULL
  , PRIMARY KEY (D_NAME)
)
;

-- Table DEPUTAT_ACCOUNT
CREATE TABLE Planning_Tool.DEPUTAT_ACCOUNT (
  ACC_ID INT NOT NULL,
  FK_TEACHER INT NOT NULL,
  FK_SEMESTER_PLANNING INT NOT NULL,
  ACC_BASELINE_HOURS DECIMAL(5,2),
  ACC_CREDIT_HOURS DECIMAL(5,2),
  ACC_DEBIT_HOURS DECIMAL(5,2),
  ACC_BALANCE DECIMAL(5,2),
  ACC_CARRYOVER DECIMAL(5,2)
  , PRIMARY KEY (ACC_ID)
)
;

-- Table LECTURER
CREATE TABLE Planning_Tool.LECTURER (
  T_ID INT NOT NULL,
  L_SUPERVISOR INT NOT NULL,
  L_STREET_ADDRESS VARCHAR(100),
  L_CITY VARCHAR(30),
  L_ZIP VARCHAR(30)
  , PRIMARY KEY (T_ID)
)
;

-- Table OFFERING
CREATE TABLE Planning_Tool.OFFERING (
  O_ID INT NOT NULL,
  FK_SUBJECT VARCHAR(11) NOT NULL,
  FK_SEMESTER_PLANNING INT NOT NULL,
  O_PLANNED_HOURS DECIMAL(5,2) NOT NULL,
  O_TYPE SMALLINT
  , PRIMARY KEY (O_ID)
)
;

-- Table OFFERING_ASSIGNMENT
CREATE TABLE Planning_Tool.OFFERING_ASSIGNMENT (
  OA_ID INT NOT NULL,
  FK_OFFERING INT NOT NULL,
  FK_TEACHER INT NOT NULL,
  OA_ROLE VARCHAR(10),
  OA_ASSIGNED_HOURS DECIMAL(5,2)
  , PRIMARY KEY (OA_ID)
)
;

-- Table POSITION
CREATE TABLE Planning_Tool.POSITION (
  PO_ID INT NOT NULL,
  PO_NAME VARCHAR(50) NOT NULL
  , PRIMARY KEY (PO_ID)
)
;

-- Table POSITION_PROFESSOR
CREATE TABLE Planning_Tool.POSITION_PROFESSOR (
  P_ID INT NOT NULL,
  PO_ID INT NOT NULL,
  TERM VARCHAR(6) NOT NULL,
  CREDIT_HOURS DECIMAL(5,2) NOT NULL
  , PRIMARY KEY (P_ID, PO_ID, TERM)
)
;

-- Table PROFESSOR
CREATE TABLE Planning_Tool.PROFESSOR (
  P_ID INT NOT NULL,
  P_CREDIT_HOUR_ACCOUNT INT,
  P_ROOM VARCHAR(10) NOT NULL
  , PRIMARY KEY (P_ID)
)
;

-- Table PROGRAMM_SUBJECT_REQUIREMENT
CREATE TABLE Planning_Tool.PROGRAMM_SUBJECT_REQUIREMENT (
  PSR_ID INT NOT NULL,
  FK_STUDY_PROGRAM VARCHAR(3) NOT NULL,
  FK_SUBJECT VARCHAR(11) NOT NULL,
  FK_SEMESTER_PLANNING INT NOT NULL,
  PSR_REQUIRED_HOURS DECIMAL(5,2),
  PSR_TARGET_SEMESTER INT NOT NULL,
  PSR_ESTIMATED_NEEDS VARCHAR(100)
  , PRIMARY KEY (PSR_ID)
)
;

-- Table SEMESTER_PLANNING
CREATE TABLE Planning_Tool.SEMESTER_PLANNING (
  SP_ID INT NOT NULL,
  SP_TERM VARCHAR(6) NOT NULL,
  SP_VERSION_NR INT NOT NULL,
  SP_IS_FINAL SMALLINT NOT NULL
  , PRIMARY KEY (SP_ID)
)
;

-- Table SERVICE_REQUEST
CREATE TABLE Planning_Tool.SERVICE_REQUEST (
  SR_ID INT NOT NULL,
  FK_SUBJECT VARCHAR(11) NOT NULL,
  FK_SEMESTER_PLANNING INT NOT NULL,
  SR_EXPORTING_FACULTY VARCHAR(3) NOT NULL,
  SR_IMPORTING_FACULTY VARCHAR(3) NOT NULL,
  SR_WEEKLY_HOURS DECIMAL(5,2),
  SR_STATUS VARCHAR(4)
  , PRIMARY KEY (SR_ID)
)
;

-- Table STUDY_PROGRAM
CREATE TABLE Planning_Tool.STUDY_PROGRAM (
  ST_NAME VARCHAR(3) NOT NULL,
  ST_DEPARTMENT VARCHAR(3) NOT NULL
  , PRIMARY KEY (ST_NAME)
)
;

-- Table SUBJECT
CREATE TABLE Planning_Tool.SUBJECT (
  S_NR VARCHAR(11) NOT NULL,
  S_STUDY_PROGRAM VARCHAR(3) NOT NULL,
  S_NAME VARCHAR(100) NOT NULL,
  S_SEMESTER INT NOT NULL,
  S_STUPO_HOURS DECIMAL(5,2) NOT NULL,
  S_SCHEDULE_HOURS DECIMAL(5,2) NOT NULL,
  S_COMMENT VARCHAR(100),
  S_TYPE VARCHAR(14) NOT NULL
  , PRIMARY KEY (S_NR)
)
;

-- Table TEACHER
CREATE TABLE Planning_Tool.TEACHER (
  T_ID INT NOT NULL,
  T_DEPARTMENT VARCHAR(3) NOT NULL,
  T_NAME VARCHAR(40) NOT NULL,
  T_LASTNAME VARCHAR(40) NOT NULL,
  T_NOTES VARCHAR(100),
  T_ISPROFESSOR SMALLINT NOT NULL
  , PRIMARY KEY (T_ID)
)
;

ALTER TABLE Planning_Tool.COURSE ADD CONSTRAINT fk_course_teacher FOREIGN KEY (C_TEACHER) REFERENCES Planning_Tool.TEACHER (T_ID);
ALTER TABLE Planning_Tool.COURSE ADD CONSTRAINT fk_course_subject FOREIGN KEY (C_SUBJECT) REFERENCES Planning_Tool.SUBJECT (S_NR);
ALTER TABLE Planning_Tool.COURSE ADD CONSTRAINT fk_course_offering FOREIGN KEY (FK_OFFERING) REFERENCES Planning_Tool.OFFERING (O_ID);
ALTER TABLE Planning_Tool.DEPUTAT_ACCOUNT ADD CONSTRAINT fk_deputat_account_teacher FOREIGN KEY (FK_TEACHER) REFERENCES Planning_Tool.TEACHER (T_ID);
ALTER TABLE Planning_Tool.DEPUTAT_ACCOUNT ADD CONSTRAINT fk_deputat_account FOREIGN KEY (FK_SEMESTER_PLANNING) REFERENCES Planning_Tool.SEMESTER_PLANNING (SP_ID);
ALTER TABLE Planning_Tool.LECTURER ADD CONSTRAINT fk_lecturer_lecturer FOREIGN KEY (T_ID) REFERENCES Planning_Tool.TEACHER (T_ID);
ALTER TABLE Planning_Tool.LECTURER ADD CONSTRAINT fk_LECTURER_SUPERVISOR FOREIGN KEY (L_SUPERVISOR) REFERENCES Planning_Tool.TEACHER (T_ID);
ALTER TABLE Planning_Tool.OFFERING ADD CONSTRAINT fk_offering_subject FOREIGN KEY (FK_SUBJECT) REFERENCES Planning_Tool.SUBJECT (S_NR);
ALTER TABLE Planning_Tool.OFFERING ADD CONSTRAINT fk_offering_semester_planning FOREIGN KEY (FK_SEMESTER_PLANNING) REFERENCES Planning_Tool.SEMESTER_PLANNING (SP_ID);
ALTER TABLE Planning_Tool.OFFERING_ASSIGNMENT ADD CONSTRAINT fk_offering_assignment FOREIGN KEY (FK_OFFERING) REFERENCES Planning_Tool.OFFERING (O_ID);
ALTER TABLE Planning_Tool.OFFERING_ASSIGNMENT ADD CONSTRAINT fk_offering_assignment_teacher FOREIGN KEY (FK_TEACHER) REFERENCES Planning_Tool.TEACHER (T_ID);
ALTER TABLE Planning_Tool.POSITION_PROFESSOR ADD CONSTRAINT fk_postion_professor_professor FOREIGN KEY (P_ID) REFERENCES Planning_Tool.PROFESSOR (P_ID);
ALTER TABLE Planning_Tool.POSITION_PROFESSOR ADD CONSTRAINT fk_position_professor_position FOREIGN KEY (PO_ID) REFERENCES Planning_Tool.POSITION (PO_ID);
ALTER TABLE Planning_Tool.PROFESSOR ADD CONSTRAINT fk_professor_teacher FOREIGN KEY (P_ID) REFERENCES Planning_Tool.TEACHER (T_ID);
ALTER TABLE Planning_Tool.PROGRAMM_SUBJECT_REQUIREMENT ADD CONSTRAINT fk_programm_subject_requirement FOREIGN KEY (FK_STUDY_PROGRAM) REFERENCES Planning_Tool.STUDY_PROGRAM (ST_NAME);
ALTER TABLE Planning_Tool.PROGRAMM_SUBJECT_REQUIREMENT ADD CONSTRAINT fk_programm_subject_requirement1 FOREIGN KEY (FK_SUBJECT) REFERENCES Planning_Tool.SUBJECT (S_NR);
ALTER TABLE Planning_Tool.PROGRAMM_SUBJECT_REQUIREMENT ADD CONSTRAINT fk_programm_subject_requirement2 FOREIGN KEY (FK_SEMESTER_PLANNING) REFERENCES Planning_Tool.SEMESTER_PLANNING (SP_ID);
ALTER TABLE Planning_Tool.SERVICE_REQUEST ADD CONSTRAINT fk_service_request_subjects FOREIGN KEY (FK_SUBJECT) REFERENCES Planning_Tool.SUBJECT (S_NR);
ALTER TABLE Planning_Tool.SERVICE_REQUEST ADD CONSTRAINT fk_service_request FOREIGN KEY (FK_SEMESTER_PLANNING) REFERENCES Planning_Tool.SEMESTER_PLANNING (SP_ID);
ALTER TABLE Planning_Tool.SERVICE_REQUEST ADD CONSTRAINT fk_service_request_department FOREIGN KEY (SR_EXPORTING_FACULTY) REFERENCES Planning_Tool.DEPARTMENT (D_NAME);
ALTER TABLE Planning_Tool.SERVICE_REQUEST ADD CONSTRAINT fk_service_request_department_import FOREIGN KEY (SR_IMPORTING_FACULTY) REFERENCES Planning_Tool.DEPARTMENT (D_NAME);
ALTER TABLE Planning_Tool.SUBJECT ADD CONSTRAINT fk_subject_study_program FOREIGN KEY (S_STUDY_PROGRAM) REFERENCES Planning_Tool.STUDY_PROGRAM (ST_NAME);
ALTER TABLE Planning_Tool.TEACHER ADD CONSTRAINT fk_teacher_department FOREIGN KEY (T_DEPARTMENT) REFERENCES Planning_Tool.DEPARTMENT (D_NAME);