-- Generated DB2 DDL from dbschema/normalizedschema.dbs
-- Schema: public

CREATE SCHEMA public;

-- Table DEPARTMENT
CREATE TABLE public.DEPARTMENT (
  D_NAME VARCHAR(100) NOT NULL
  , PRIMARY KEY (D_NAME)
)
;

-- Table DEPUTAT_ACCOUNT
CREATE TABLE public.DEPUTAT_ACCOUNT (
  ACC_ID INT NOT NULL,
  FK_T_ID INT,
  FK_SP_ID INT,
  ACC_BASELINE_HOURS DECIMAL(4,2),
  ACC_CARRYOVER DECIMAL(4,2)
  , PRIMARY KEY (ACC_ID)
)
;

-- Table LECTURER
CREATE TABLE public.LECTURER (
  T_ID INT NOT NULL,
  L_STREET_ADDRESS VARCHAR(255),
  L_SUPERVISOR INT
  , PRIMARY KEY (T_ID)
)
;

-- Table OFFERING
CREATE TABLE public.OFFERING (
  O_ID INT NOT NULL,
  FK_S_ID INT,
  FK_SP_ID INT,
  O_PLANNED_HOURS INT
  , PRIMARY KEY (O_ID)
)
;

-- Table OFFERING_ASSIGNMENT
CREATE TABLE public.OFFERING_ASSIGNMENT (
  OA_ID INT NOT NULL,
  FK_O_ID INT,
  FK_T_ID INT,
  OA_ASSIGNED_HOURS DECIMAL(4,2),
  OA_ACTUAL_HOURS DECIMAL(4,2),
  OA_ROLE VARCHAR(50)
  , PRIMARY KEY (OA_ID)
)
;

-- Table POSITION
CREATE TABLE public.POSITION (
  PO_ID INT NOT NULL,
  PO_NAME VARCHAR(100) NOT NULL
  , PRIMARY KEY (PO_ID)
)
;

-- Table POSITION_SEMESTER
CREATE TABLE public.POSITION_SEMESTER (
  PS_ID INT NOT NULL,
  FK_PO_ID INT NOT NULL,
  FK_SP_ID INT NOT NULL
  , PRIMARY KEY (PS_ID)
)
;

-- Table POSITION_ASSIGNMENT
CREATE TABLE public.POSITION_ASSIGNMENT (
  PA_ID INT NOT NULL,
  FK_PS_ID INT NOT NULL,
  FK_P_ID INT NOT NULL,
  PA_REDUCTION_HOURS DECIMAL(4,2) NOT NULL
  , PRIMARY KEY (PA_ID)
)
;

-- Table POSTAL_CODE
CREATE TABLE public.POSTAL_CODE (
  ZIP VARCHAR(10) NOT NULL,
  CITY VARCHAR(100) NOT NULL
  , PRIMARY KEY (ZIP)
)
;

-- Table PROFESSOR
CREATE TABLE public.PROFESSOR (
  T_ID INT NOT NULL,
  P_ROOM VARCHAR(50)
  , PRIMARY KEY (T_ID)
)
;

-- Table SEMESTER_PLANNING
CREATE TABLE public.SEMESTER_PLANNING (
  SP_ID INT NOT NULL,
  SP_TERM VARCHAR(20) NOT NULL,
  SP_VERSION_NR INT,
  SP_IS_FINAL SMALLINT
  , PRIMARY KEY (SP_ID)
)
;

-- Table SERVICE_REQUEST
CREATE TABLE public.SERVICE_REQUEST (
  SR_ID INT NOT NULL,
  FK_S_ID INT,
  FK_REQUESTING_D_NAME VARCHAR(100),
  FK_PROVIDING_D_NAME VARCHAR(100),
  SR_HOURS DECIMAL(4,2) NOT NULL,
  SR_STATUS VARCHAR(50),
  FK_SEMESTER INT,
  SR_NOTES VARCHAR(100)
  , PRIMARY KEY (SR_ID)
)
;

-- Table STUDY_PROGRAM
CREATE TABLE public.STUDY_PROGRAM (
  ST_NAME VARCHAR(100) NOT NULL,
  FK_D_NAME VARCHAR(100)
  , PRIMARY KEY (ST_NAME)
)
;

-- Table SUBJECT
CREATE TABLE public.SUBJECT (
  S_ID INT NOT NULL,
  S_NAME VARCHAR(255) NOT NULL,
  S_STUPO_HOURS DECIMAL(4,2),
  S_SEMESTER INT NOT NULL,
  FK_ST_NAME VARCHAR(100),
  S_NOTES VARCHAR(100),
  S_TYPE VARCHAR(1) NOT NULL
  , PRIMARY KEY (S_ID)
)
;

-- Table TEACHER
CREATE TABLE public.TEACHER (
  T_ID INT NOT NULL,
  T_NAME VARCHAR(100),
  T_LASTNAME VARCHAR(100),
  FK_D_NAME VARCHAR(100),
  FK_ZIP VARCHAR(10),
  T_NOTES VARCHAR(100),
  T_IS_ACTIVE SMALLINT NOT NULL
  , PRIMARY KEY (T_ID)
)
;

ALTER TABLE public.DEPARTMENT ADD CONSTRAINT fk_DEPARTMENT_TEACHER FOREIGN KEY (D_NAME) REFERENCES public.TEACHER (FK_D_NAME);
ALTER TABLE public.DEPARTMENT ADD CONSTRAINT fk_DEPARTMENT_STUDY_PROGRAM FOREIGN KEY (D_NAME) REFERENCES public.STUDY_PROGRAM (FK_D_NAME);
ALTER TABLE public.DEPARTMENT ADD CONSTRAINT fk_DEPARTMENT_SERVICE_REQUEST FOREIGN KEY (D_NAME) REFERENCES public.SERVICE_REQUEST (FK_REQUESTING_D_NAME);
ALTER TABLE public.DEPARTMENT ADD CONSTRAINT fk_DEPARTMENT_SERVICE_PROVIDE_0 FOREIGN KEY (D_NAME) REFERENCES public.SERVICE_REQUEST (FK_PROVIDING_D_NAME);
ALTER TABLE public.LECTURER ADD CONSTRAINT fk_LECTURER_PROFESSOR FOREIGN KEY (L_SUPERVISOR) REFERENCES public.PROFESSOR (T_ID);
ALTER TABLE public.OFFERING ADD CONSTRAINT fk_OFFERING_OFFERING_ASSIGNMENT FOREIGN KEY (O_ID) REFERENCES public.OFFERING_ASSIGNMENT (FK_O_ID);
ALTER TABLE public.POSITION ADD CONSTRAINT fk_POSITION_POSITION_SEMESTER FOREIGN KEY (PO_ID) REFERENCES public.POSITION_SEMESTER (FK_PO_ID);
ALTER TABLE public.POSITION_SEMESTER ADD CONSTRAINT fk_POSITION_SEMESTER_POSITION_ASSIGNMENT FOREIGN KEY (PS_ID) REFERENCES public.POSITION_ASSIGNMENT (FK_PS_ID);
ALTER TABLE public.POSTAL_CODE ADD CONSTRAINT fk_POSTAL_CODE_TEACHER FOREIGN KEY (ZIP) REFERENCES public.TEACHER (FK_ZIP);
ALTER TABLE public.PROFESSOR ADD CONSTRAINT fk_PROFESSOR_POSITION_ASSIGNMENT FOREIGN KEY (T_ID) REFERENCES public.POSITION_ASSIGNMENT (FK_P_ID);
ALTER TABLE public.SEMESTER_PLANNING ADD CONSTRAINT fk_SEMESTER_PLANNING_OFFERING FOREIGN KEY (SP_ID) REFERENCES public.OFFERING (FK_SP_ID);
ALTER TABLE public.SEMESTER_PLANNING ADD CONSTRAINT fk_SEMESTER_PLANNING_DEPUTAT_ACCOUNT FOREIGN KEY (SP_ID) REFERENCES public.DEPUTAT_ACCOUNT (FK_SP_ID);
ALTER TABLE public.SEMESTER_PLANNING ADD CONSTRAINT fk_SEMESTER_PLANNING_SERVICE_REQUEST FOREIGN KEY (SP_ID) REFERENCES public.SERVICE_REQUEST (FK_SEMESTER);
ALTER TABLE public.SEMESTER_PLANNING ADD CONSTRAINT fk_SEMESTER_PLANNING_POSITION_SEMESTER FOREIGN KEY (SP_ID) REFERENCES public.POSITION_SEMESTER (FK_SP_ID);
ALTER TABLE public.STUDY_PROGRAM ADD CONSTRAINT fk_STUDY_PROGRAM_SUBJECT FOREIGN KEY (ST_NAME) REFERENCES public.SUBJECT (FK_ST_NAME);
ALTER TABLE public.SUBJECT ADD CONSTRAINT fk_SUBJECT_OFFERING FOREIGN KEY (S_ID) REFERENCES public.OFFERING (FK_S_ID);
ALTER TABLE public.SUBJECT ADD CONSTRAINT fk_SUBJECT_SERVICE_REQUEST FOREIGN KEY (S_ID) REFERENCES public.SERVICE_REQUEST (FK_S_ID);
ALTER TABLE public.TEACHER ADD CONSTRAINT fk_TEACHER_PROFESSOR FOREIGN KEY (T_ID) REFERENCES public.PROFESSOR (T_ID);
ALTER TABLE public.TEACHER ADD CONSTRAINT fk_TEACHER_LECTURER FOREIGN KEY (T_ID) REFERENCES public.LECTURER (T_ID);
ALTER TABLE public.TEACHER ADD CONSTRAINT fk_TEACHER_OFFERING_ASSIGNMENT FOREIGN KEY (T_ID) REFERENCES public.OFFERING_ASSIGNMENT (FK_T_ID);
ALTER TABLE public.TEACHER ADD CONSTRAINT fk_TEACHER_DEPUTAT_ACCOUNT FOREIGN KEY (T_ID) REFERENCES public.DEPUTAT_ACCOUNT (FK_T_ID);