-- Create the database
CREATE DATABASE PLANTOOL;

-- Connect to the new database
CONNECT TO PLANTOOL;

-- Create the schema
CREATE SCHEMA PLANNING_TOOL;

-- Set the current schema
SET CURRENT SCHEMA = PLANNING_TOOL;

-- Create all tables with proper DB2 syntax

-- Base tables (no dependencies)
CREATE TABLE DEPARTMENT (
    D_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (D_NAME)
);

CREATE TABLE POSTAL_CODE (
    ZIP VARCHAR(10) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PRIMARY KEY (ZIP)
);

CREATE TABLE SEMESTER_PLANNING (
    SP_ID INT NOT NULL,
    SP_TERM VARCHAR(20) NOT NULL,
    SP_VERSION_NR INT,
    SP_IS_FINAL SMALLINT NOT NULL,
    PRIMARY KEY (SP_ID)
);

CREATE TABLE POSITION (
    PO_ID INT NOT NULL,
    PO_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (PO_ID)
);

-- First level dependencies
CREATE TABLE TEACHER (
    T_ID INT NOT NULL,
    T_NAME VARCHAR(100),
    T_LASTNAME VARCHAR(100) NOT NULL,
    FK_D_NAME VARCHAR(100),
    FK_ZIP VARCHAR(10),
    T_NOTES VARCHAR(100),
    T_IS_ACTIVE SMALLINT NOT NULL,
    PRIMARY KEY (T_ID),
    FOREIGN KEY (FK_D_NAME) REFERENCES DEPARTMENT(D_NAME),
    FOREIGN KEY (FK_ZIP) REFERENCES POSTAL_CODE(ZIP)
);

CREATE TABLE PROFESSOR (
    T_ID INT NOT NULL,
    P_ROOM VARCHAR(50),
    PRIMARY KEY (T_ID),
    FOREIGN KEY (T_ID) REFERENCES TEACHER(T_ID)
);

CREATE TABLE LECTURER (
    T_ID INT NOT NULL,
    L_STREET_ADDRESS VARCHAR(255),
    PRIMARY KEY (T_ID),
    FOREIGN KEY (T_ID) REFERENCES TEACHER(T_ID)
);

CREATE TABLE STUDY_PROGRAM (
    ST_NAME VARCHAR(100) NOT NULL,
    FK_D_NAME VARCHAR(100),
    PRIMARY KEY (ST_NAME),
    FOREIGN KEY (FK_D_NAME) REFERENCES DEPARTMENT(D_NAME)
);

CREATE TABLE SUBJECT (
    S_ID INT NOT NULL,
    S_NAME VARCHAR(255) NOT NULL,
    S_STUPO_HOURS DECIMAL(4,2),
    S_SEMESTER INT NOT NULL,
    FK_ST_NAME VARCHAR(100),
    S_NOTES VARCHAR(100),
    S_TYPE VARCHAR(1) NOT NULL,
    PRIMARY KEY (S_ID),
    FOREIGN KEY (FK_ST_NAME) REFERENCES STUDY_PROGRAM(ST_NAME)
);

-- Second level dependencies
CREATE TABLE OFFERING (
    O_ID INT NOT NULL,
    FK_S_ID INT,
    FK_SP_ID INT,
    O_PLANNED_HOURS INT,
    PRIMARY KEY (O_ID),
    FOREIGN KEY (FK_S_ID) REFERENCES SUBJECT(S_ID),
    FOREIGN KEY (FK_SP_ID) REFERENCES SEMESTER_PLANNING(SP_ID)
);

CREATE TABLE OFFERING_ASSIGNMENT (
    OA_ID INT NOT NULL,
    FK_O_ID INT,
    FK_T_ID INT,
    OA_ASSIGNED_HOURS DECIMAL(4,2),
    OA_ROLE VARCHAR(50),
    PRIMARY KEY (OA_ID),
    FOREIGN KEY (FK_O_ID) REFERENCES OFFERING(O_ID),
    FOREIGN KEY (FK_T_ID) REFERENCES TEACHER(T_ID)
);

CREATE TABLE DEPUTAT_ACCOUNT (
    ACC_ID INT NOT NULL,
    FK_T_ID INT,
    FK_SP_ID INT,
    ACC_BASELINE_HOURS DECIMAL(4,2),
    ACC_CARRYOVER DECIMAL(4,2),
    PRIMARY KEY (ACC_ID),
    FOREIGN KEY (FK_T_ID) REFERENCES TEACHER(T_ID),
    FOREIGN KEY (FK_SP_ID) REFERENCES SEMESTER_PLANNING(SP_ID)
);

CREATE TABLE SERVICE_REQUEST (
    SR_ID INT NOT NULL,
    FK_S_ID INT,
    FK_REQUESTING_D_NAME VARCHAR(100),
    FK_PROVIDING_D_NAME VARCHAR(100),
    SR_HOURS DECIMAL(4,2) NOT NULL,
    SR_STATUS VARCHAR(50),
    FK_SEMESTER INT,
    SR_NOTES VARCHAR(100),
    PRIMARY KEY (SR_ID),
    FOREIGN KEY (FK_S_ID) REFERENCES SUBJECT(S_ID),
    FOREIGN KEY (FK_REQUESTING_D_NAME) REFERENCES DEPARTMENT(D_NAME),
    FOREIGN KEY (FK_PROVIDING_D_NAME) REFERENCES DEPARTMENT(D_NAME),
    FOREIGN KEY (FK_SEMESTER) REFERENCES SEMESTER_PLANNING(SP_ID)
);

CREATE TABLE POSITION_SEMESTER (
    PS_ID INT NOT NULL,
    FK_PO_ID INT NOT NULL,
    FK_SP_ID INT NOT NULL,
    PRIMARY KEY (PS_ID),
    FOREIGN KEY (FK_PO_ID) REFERENCES POSITION(PO_ID),
    FOREIGN KEY (FK_SP_ID) REFERENCES SEMESTER_PLANNING(SP_ID)
);

CREATE TABLE POSITION_ASSIGNMENT (
    PA_ID INT NOT NULL,
    FK_PS_ID INT NOT NULL,
    FK_P_ID INT NOT NULL,
    PA_REDUCTION_HOURS DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (PA_ID),
    FOREIGN KEY (FK_PS_ID) REFERENCES POSITION_SEMESTER(PS_ID),
    FOREIGN KEY (FK_P_ID) REFERENCES PROFESSOR(T_ID)
);

-- Unique indexes from the normalized schema
CREATE UNIQUE INDEX UNQ_POSITION_SEMESTER ON POSITION_SEMESTER(FK_PO_ID, FK_SP_ID);
CREATE UNIQUE INDEX UNQ_POSITION_ASSIGNMENT ON POSITION_ASSIGNMENT(FK_PS_ID, FK_P_ID);

COMMIT;

-- Show created tables
SELECT TABNAME FROM SYSCAT.TABLES WHERE TABSCHEMA = 'PLANNING_TOOL' ORDER BY TABNAME;
